package edu.csusm.capstone.timeseriesannotator.View;

import edu.csusm.capstone.timeseriesannotator.Controller.AddSeriesAction;
import edu.csusm.capstone.timeseriesannotator.Controller.Chart;
import edu.csusm.capstone.timeseriesannotator.Controller.Controller;
import edu.csusm.capstone.timeseriesannotator.Controller.ImportDataAction;
import java.awt.Color;
import java.awt.event.ActionListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartMouseEvent;
import org.jfree.chart.ChartMouseListener;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author josef
 */
public class ChartDisplay extends javax.swing.JPanel implements ActionListener {

    AnnotateChartPanel emptyChart;
    AppFrame frame;
    Chart chartStruct;
    Controller control;
    XYPlot plot;

    /**
     * Creates new form ChartPanel
     */
    public ChartDisplay(AppFrame f) {
        this.frame = f;
        initComponents();
        startChart();
        
    }

    private void startChart() {
        XYSeriesCollection emptyData = new XYSeriesCollection();

        String chartTitle = "Data";
        String xAxisLabel = "X";
        String yAxisLabel = "Y";

        JFreeChart chart = ChartFactory.createXYLineChart(chartTitle,
                xAxisLabel, yAxisLabel, emptyData);

        emptyChart = new AnnotateChartPanel(chart);
        emptyChart.setZoomOutlinePaint(Color.BLACK);
        emptyChart.setMouseWheelEnabled(true);

        XYPlot plot = chart.getXYPlot();
        plot.setRangePannable(true);
        plot.setDomainPannable(true);

        jPanel2.add(emptyChart);
    }

    public XYPlot returnPlot() {
        JFreeChart chart = emptyChart.getChart();
        return chart.getXYPlot();
    }

    public void setChart(AnnotateChartPanel p) {
        if (emptyChart.getParent() == jPanel2) {
            jPanel2.remove(emptyChart);
        }
        emptyChart = p;
        
        emptyChart.setZoomOutlinePaint(Color.BLACK);

        emptyChart.addChartMouseListener(new ChartMouseListener() {
            @Override
            public void chartMouseClicked(ChartMouseEvent event) {
                if (event.getTrigger().getClickCount() == 2) {
                    emptyChart.restoreAutoBounds();
                }
            }

            @Override
            public void chartMouseMoved(ChartMouseEvent event) {

            }
        });

        jPanel2.add(emptyChart);
        validate();
        repaint();
        setVisible(true);
    }

    public void setChartData(Chart c) {
        this.chartStruct = c;
        this.plot = chartStruct.getPlot();
        chartStruct.setDomainAxis(this.plot.getDomainAxis());
        chartStruct.setRangeAxis(this.plot.getRangeAxis());
        control = new Controller(emptyChart);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        removeChartButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SyncButton = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(new java.awt.BorderLayout());

        removeChartButton.setBackground(new java.awt.Color(204, 0, 0));
        removeChartButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeChartButton.setForeground(new java.awt.Color(255, 255, 255));
        removeChartButton.setText("X");
        removeChartButton.setName("removeChartButton");
        removeChartButton.setToolTipText("");
        removeChartButton.addActionListener(this);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Add Series");
        jButton2.setToolTipText("");
        jButton2.addActionListener(this);

        jPanel2.setLayout(new java.awt.BorderLayout());

        SyncButton.setText("Sync Chart");
        SyncButton.addActionListener(this);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(SyncButton)
                .addGap(18, 18, 18)
                .addComponent(removeChartButton)
                .addGap(15, 15, 15))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeChartButton)
                    .addComponent(jButton2)
                    .addComponent(SyncButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == removeChartButton) {
            ChartDisplay.this.removeChartButtonActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            ChartDisplay.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == SyncButton) {
            ChartDisplay.this.SyncButtonActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void removeChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChartButtonActionPerformed
        if (frame.charts.size() > 1) {
            frame.removeChart(this);
        } else {
            frame.removeChart(this);
            frame.initialChart();
        }
    }//GEN-LAST:event_removeChartButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (chartStruct != null) {
            ActionListener addAction = new AddSeriesAction(this.chartStruct, this);
            addAction.actionPerformed(evt);
        } else {
            ActionListener importAction = new ImportDataAction(frame.getImportChooser(), this);
            importAction.actionPerformed(evt);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SyncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SyncButtonActionPerformed
        if(SyncButton.isSelected()){
            control.addSync(chartStruct.getPlot(), chartStruct);
        }
        else{
            control.removeSync(plot);
            plot.setDomainAxis(chartStruct.getDomainAxis());
            plot.setRangeAxis(chartStruct.getRangeAxis());
        }
    }//GEN-LAST:event_SyncButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SyncButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removeChartButton;
    // End of variables declaration//GEN-END:variables
}
